//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApps.Infrastructure.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificat
    {
        public int IdCertificat { get; set; }
        public int IdParticipant { get; set; }
        public System.DateTime DateDelivrance { get; set; }
    
        public virtual Participant Participant { get; set; }
    }
}
