//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApps.Infrastructure.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultat
    {
        public int IdResultat { get; set; }
        public int IdModuleInscription { get; set; }
        public int IdExamen { get; set; }
        public Nullable<int> Points { get; set; }
        public bool EstPresent { get; set; }
        public bool ParticipantRéussi { get; set; }
    
        public virtual Examan Examan { get; set; }
        public virtual ModuleInscription ModuleInscription { get; set; }
    }
}
